### ISSUE TITLE
403 - Require app_id or client_id on "Login"

### ISSUE THREAD

**Issue by renestalder** [anopensourceguy/TodoistN1#10]
When I hit the "Login to todoist" Button, I get this:

![screen shot 2016-04-22 at 11 08 59](https://cloud.githubusercontent.com/assets/105358/14737101/9fc35b40-087a-11e6-8221-5fd2e4810468.png)

![screen shot 2016-04-22 at 11 09 19](https://cloud.githubusercontent.com/assets/105358/14737114/abca7630-087a-11e6-87b5-773bf9747884.png)

**Comment by anopensourceguy** [comment]
@TampaDoug 
    Go to https://developer.todoist.com/appconsole.html
    Sign in with your Todoist account
    Click the "Create new app" button
    Choose a name, it doesn't really matter what, but for simplicity sake, I recommend something that includes N1 in it, perhaps "TodoistN1". Go ahead and leave the other option blank then press create.
    From this new screen, the only things you need to worry about are the Client ID, the Secret Key and that OAuth Redirect URL field. The Client ID and Secret Key are generated for you, but you need to put something in for the redirect url. You can use whatever you would like, just use something like "http://yourname.com/todoist".
    Ignore everything else, but keep this window open, you will need it shortly.
    Go download this plugin now from here (I'm assuming you have already installed Nylas N1, if not, go do that as well!)
    Extract the file, open the folder that you extracted and navigate to ToDoistN1 -> lib -> my-message-sidebar.cjsx and open it in your favourite text editor, I like sublime text 3.
    Now, around line 13, you should see: client_id: "", client_secret: "", Go ahead and add in those keys from your Todoist Developers account, they are the ones that were generated for you.

    Next, around line 128 (Or just ctrl+f/cmd+f "uri"), you should find:

    .send({ client_id: options.client_id, client_secret: options.client_secret, code: code, redirect_uri: "**http://www.iamsupratim.com/n1todoist**" })

OR

.send({ client_id: options.client_id, client_secret: options.client_secret, code: code, redirect_uri: "**yourredirecturlhere**" })
Go ahead and replace either the http://www.iamsupratim.com/n1todoist or yourredirecturlhere with that OAuth Redirect URL you created on the Todoist Developers site (the place where you generated those keys).

11) Save that file and close it.
12) Open Nylas N1 and navigate to Developer -> Install a plugin manually...
13) This should open a finder/explorer window. Simply direct it to the folder you extracted, for example ~/downloads/TodoistN1-1.0 and click open.
14) Once N1 says it has installed, close the program then re-open it (Ignore what it says about not needing to close it).
15) If you followed these steps, you should find that there is a Sign In to Todoist button on your sidebar, click it, sign in normally and give it your permissions. Ta-da!

NOTE: As of this build, after you have signed in, pressing the SEND TO TODOIST button doesn't give any indication that it did anything. Don't press it multiple times, it did work and it did send it to your Todoist account, just check under inbox and you should see your email's name sitting in you inbox, ready to be edited!

**Comment by renestalder** [comment]
That sounds like a lot of work to do for me to get this running. Is this a temporary workaround or just the wanted behaviour?

**Comment by anopensourceguy** [comment]
See the thing is. I made this extension open source so I cannot give my api
keys. So essentially you just have to make an app in todoist app console
yourself and use those credentials in the said places in the file. That's
it good sir

**Comment by renestalder** [comment]
I understand. I'm not just quite sure. Normally, if you use oAuth the user shouldn't have to create a new app. In my understanding, you have to register one app for this extension and getting a client_id. With the oAuth API you just send this client_id to the api and getting back a user token. I mean that's the purpose of the whole app registration and oAuth process.

**Comment by anopensourceguy** [comment]
But in essence the app id and client id will be that of the app I created
right?  So the source code will be showing the client id and the Secret
right?

**Comment by renestalder** [comment]
okay, I see your point. Since I only develop applications which are on a server, this wasn't a problem yet. So in case of code that's directly delivered to the client, there seems to be a need for a authentication wrapper which is running on a server. The app would request the program logic on the server where the client_id is stored and this part will handle the authentication process to the oAuth API of the external provider.

Anyway, actually it seems to be too complicated to get this plugin running. You should at least add the full description above to the readme.

**Comment by anopensourceguy** [comment]
Yeah man. Just getting it out to help people with plugin development code
examples. I use it myself for task delegation within the email client

**Comment by renestalder** [comment]
Keep going 👍  I think the Todoist Plugin is a very good idea.

**Comment by torniker** [comment]
I did everything you have described, but on step 15 when I click the button there is an error: 

`/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306 TypeError: authWindow.loadUrl is not a function
    at MyMessageSidebar._loginToTodoist (/Users/koko/.nylas/packages/Todoist/lib/my-message-sidebar.cjsx:138:17)
    at /Users/koko/.nylas/packages/Todoist/lib/my-message-sidebar.cjsx:1:1
    at Object.invokeGuardedCallback (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:26:12)
    at executeDispatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:87:21)
    at Object.executeDispatchesInOrder (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110:5)
    at executeDispatchesAndRelease (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:42:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:53:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:24:9)
    at Object.processEventQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:215:7)
    at runEventQueueInBatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
    at handleTopLevelImpl (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:73:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at Object.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:97:20)
    at dispatchEvent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:150:20)module.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306(anonymous function) @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:254
/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:52 Uncaught TypeError: authWindow.loadUrl is not a functionMyMessageSidebar._loginToTodoist @ my-message-sidebar.cjsx:138(anonymous function) @ my-message-sidebar.cjsx:1invokeGuardedCallback @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:26executeDispatch @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:87executeDispatchesInOrder @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110executeDispatchesAndRelease @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:42executeDispatchesAndReleaseTopLevel @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:53forEachAccumulated @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:24processEventQueue @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:215runEventQueueInBatch @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixi…:18handleTopLevel @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixi…:29handleTopLevelImpl @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:73perform @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136batchedUpdates @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingS…:63batchedUpdates @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:97dispatchEvent @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:150`
